apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql
   labels:
      app: mysql
spec:
   selector:
      matchLabels:
         app: mysql
   replicas: 1
   template:
      metadata:
         labels:
            app: mysql
      spec:
         containers:
         - name: master
           image: mysql
           resources:
              requests:
                 cpu: 100m
                 memory: 100Mi
           args:
           - --default-authentication-plugin=mysql_native_password
           env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mysql-pass
                 key: password
           ports:
           - containerPort: 3306
           volumeMounts:
           - mountPath: /var/lib/mysql
             name: mysql-data
         volumes:
         - name: mysql-data
           persistentVolumeClaim:
             claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
   name: mysql
   labels:
      app: mysql
spec:
   type: NodePort
   selector:
      app: mysql
   ports:
      - port: 3306
        targetPort: 3306
#       nodePort: 3306
